apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblio
  labels:
    app: biblio
    tier: frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: biblio
            tier: frontend
    template:
        metadata:
            labels:
                app: biblio
                tier: frontend
        spec:
            containers:
                - name: biblio
                  image: mzaygar034/biblioteca:v1_1
                  env:
                    - name: MYSQL_HOST
                      value: mariadb
                    - name: MYSQL_DATABASE
                      valueFrom:
                        configMapKeyRef:
                          name: cm-mariadb
                          key: bd_name
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: secret-mariadb
                          key: passwd_user
                    - name: MYSQL_USER
                      valueFrom:
                        configMapKeyRef:
                          name: cm-mariadb
                          key: bd_user
                  ports:
                    - containerPort: 80
                      name: biblio
